name: CICD - ERP Base v17.0

on:
  push:
    branches: [ 17.0 ]
  schedule:
    - cron: '0 23 * * 0 */2' # 0 minutos, 23 horas (11:00 PM), cada dos semanas (0 domingo)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: docker login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
      - name: docker build erp base
        run: |
          cd ./docker
          docker build -f Dockerfile -t $DOCKER_USER/erp-base:17.0-latest --platform linux/amd64 .
      - name: docker push erp base latest
        run: |
          docker push $DOCKER_USER/erp-base:17.0-latest
      - name: docker cp erp base
        run: |
          docker tag $DOCKER_USER/erp-base:17.0-latest $DOCKER_USER/erp-base:17.0-${{ steps.date.outputs.date }}
      - name: docker push erp base with date
        run: |
          docker push $DOCKER_USER/erp-base:17.0-${{ steps.date.outputs.date }}